services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
    command: >
      bash -c "jenkins-plugin-cli --plugins 'docker-plugin:1274.vc0203fdf2e74 docker-workflow:621.va_73f881d9232' &&
      exec java -jar /usr/share/jenkins/jenkins.war"
volumes:
  jenkins_home:
